### PR TITLE
NATIVESVTTK

### PR DESCRIPTION
**Pull request by jhi2**

### CODE REVIEW

**Comment by rdbende** [comment]
Sorry, I'm still not sure, what's your goal with this. I can only repeat what I've said here: https://github.com/rdbende/Sun-Valley-ttk-theme/pull/132#pullrequestreview-1970155997

**Comment by jhi2** [comment]
Try this
And, BY THE WAY: THIS VERSION USES OUTDATED SETUPTOOLS AND WHY IS YOUR PYPROJECT.TOML EMPTY

**Comment by jhi2** [comment]
I know u hate this

**Comment by rdbende** [comment]
Sorry for not getting to this PR earlier. You may have noticed, that I've been quite busy in the last couple of months, and haven't got to reviewing this PR yet. However I've left pretty clear review comments in #132, and you didn't address most of them.

I indeed don't want this feature in sv-ttk, because it's still just a UI theme wrapped as a Python package to make it easier to install. I don't like the idea of adding some platform-specfic features, that have not much to do with this project, and are otherwise trivial to implement if one wants it. I will probably reject any similar requests in the future.

I also don't want to add irrelevant dependencies like CustomTkinter, as it is an entirely different project with different goals thats has nothing to do with sv-ttk.


> And, BY THE WAY: THIS VERSION USES OUTDATED SETUPTOOLS AND WHY IS YOUR PYPROJECT.TOML EMPTY

Feel free to open a pull request to update setuptools. The pyproject.toml file is empty, because I don't actually use it, but some tool I use refused to work without it. You can search in the git history to find out the reason for it.

**Comment by rdbende** [comment]
You also have to understand, that if I merge something, it adds maintenance burden, although I already don't have the capacity to maintain this project.

**Pull request closed without merging**
