### PR TITLE
Do not config menus on windows

### PR DESCRIPTION
**Pull request by Akuli**
Fixes https://github.com/Akuli/porcupine/issues/1431

I haven't tested this on Windows.

### CODE REVIEW

**Comment by rdbende** [comment]
@littlewhitecloud this should solve your issue. Can you confirm?

**Comment by littlewhitecloud** [comment]
I will test it later because I'm doing my final exam.

**Comment by littlewhitecloud** [comment]
image
It is very useful but it won't apply the dark theme if you don't add a new widget into the window.
Before:

After:
image

```python
import tkinter
import tkinter.ttk
import sv_ttk  # pip install sv-ttk

root = tkinter.Tk()
sv_ttk.set_theme('dark')  # Try removing this line

main_menu = tkinter.Menu()
root.config(menu=main_menu)

submenu = tkinter.Menu(main_menu, tearoff=False)
main_menu.add_cascade(label="File", menu=submenu)

submenu.add_command(label="New File", accelerator="Ctrl+N")
submenu.add_command(label="Open", accelerator="Ctrl+O")
submenu.add_command(label="Save", accelerator="Ctrl+S", state="disabled")
submenu.add_command(label="Save As", accelerator="Ctrl+Shift+S", state="disabled")
submenu.add_separator()
submenu.add_command(label="Close", accelerator="Ctrl+W", state="disabled")
submenu.add_command(label="Quit", accelerator="Ctrl+Q")


testbutton = tkinter.ttk.Button(root, text="test")
testbutton.pack()

root.mainloop()
```

**Comment by littlewhitecloud** [comment]
Nevermind, maybe it is vaild.

**Comment by Akuli** [comment]
I personally would prefer the menus without dark theme applied to them. You can at least clearly see what's disabled. And as rdbende said, the menu bar doesn't become dark anyway.

I'd suggest we merge this.

**Comment by littlewhitecloud** [comment]
I do think so. Maybe I had figure out where is the problem is, but I need time to do it... Just merge it first...

**Comment by rdbende** [comment]
Thanks!

**Comment by rdbende** [comment]
#127 🎉

**Comment by Valer100** [comment]
I don't know, but on Windows (at least for me), the menus still have their colors changed when the theme is set to dark. I'm using the latest version (2.6.0). I've modified ```configure_colors``` proc in ```sv.tcl``` file and the menus have now their default colors. Here's how I modified it:

```tcl
proc configure_colors {} {
  set theme [ttk::style theme use]
  if {$theme == "sun-valley-dark"} {
    ttk::style configure . \
      -background $ttk::theme::sv_dark::colors(-bg) \
      -foreground $ttk::theme::sv_dark::colors(-fg) \
      -troughcolor $ttk::theme::sv_dark::colors(-bg) \
      -focuscolor $ttk::theme::sv_dark::colors(-selbg) \
      -selectbackground $ttk::theme::sv_dark::colors(-selbg) \
      -selectforeground $ttk::theme::sv_dark::colors(-selfg) \
      -insertwidth 1 \
      -insertcolor $ttk::theme::sv_dark::colors(-fg) \
      -fieldbackground $ttk::theme::sv_dark::colors(-bg) \
      -font SunValleyBodyFont \
      -borderwidth 0 \
      -relief flat

    tk_setPalette \
      background $ttk::theme::sv_dark::colors(-bg) \
      foreground $ttk::theme::sv_dark::colors(-fg) \
      highlightColor $ttk::theme::sv_dark::colors(-selbg) \
      selectBackground $ttk::theme::sv_dark::colors(-selbg) \
      selectForeground $ttk::theme::sv_dark::colors(-selfg) \
      activeBackground $ttk::theme::sv_dark::colors(-selbg) \
      activeForeground $ttk::theme::sv_dark::colors(-selfg)

    ttk::style map . -foreground [list disabled $ttk::theme::sv_dark::colors(-disfg)]
  } elseif {$theme == "sun-valley-light"} {
    ttk::style configure . \
      -background $ttk::theme::sv_light::colors(-bg) \
      -foreground $ttk::theme::sv_light::colors(-fg) \
      -troughcolor $ttk::theme::sv_light::colors(-bg) \
      -focuscolor $ttk::theme::sv_light::colors(-selbg) \
      -selectbackground $ttk::theme::sv_light::colors(-selbg) \
      -selectforeground $ttk::theme::sv_light::colors(-selfg) \
      -insertwidth 1 \
      -insertcolor $ttk::theme::sv_light::colors(-fg) \
      -fieldbackground $ttk::theme::sv_light::colors(-bg) \
      -font SunValleyBodyFont \
      -borderwidth 0 \
      -relief flat

    tk_setPalette \
      background $ttk::theme::sv_light::colors(-bg) \
      foreground $ttk::theme::sv_light::colors(-fg) \
      highlightColor $ttk::theme::sv_light::colors(-selbg) \
      selectBackground $ttk::theme::sv_light::colors(-selbg) \
      selectForeground $ttk::theme::sv_light::colors(-selfg) \
      activeBackground $ttk::theme::sv_light::colors(-selbg) \
      activeForeground $ttk::theme::sv_light::colors(-selfg)

    ttk::style map . -foreground [list disabled $ttk::theme::sv_light::colors(-disfg)]
  }

  if {[tk windowingsystem] == "aqua" || [tk windowingsystem] == "win32"} {
    option add *Menu.background systemMenu
    option add *Menu.foreground systemMenuText
  }
}
```

**Comment by Valer100** [comment]
If you want, I can make a PR with the fix

**Pull request merged**
